#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the    
# UPS goes back on to the mains after a power failure.
# We send an email message to root to notify him.
#
#echo "running script offbattery $MSG"
EPICS_BIN=/home/pi/Apps/epics7/epics-base/bin/linux-arm
$EPICS_BIN/caput ISTTOK:central:UPS-OnBattery OFF
$EPICS_BIN/caput ISTTOK:central:UPS-Shutdown OFF

SYSADMIN=bernardo.brotas@gmail.com
HOSTNAME=`hostname`
MSG="$HOSTNAME UPS $1 Power has returned"
#
(
   echo "$MSG"
   echo " "
   /sbin/apcaccess status
) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
exit 0
