#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the UPS
# goes on batteries.
# We send an email message to root to notify him.
#

## EPICS  
EPICSBIN='/home/pi/Apps/epics7/epics-base/bin/linux-arm'
$EPICSBIN/caput ISTTOK:central:UPS-OnBattery ON

HOSTNAME=`rpi-isttok`
#SYSADMIN=bernardo.brotas@gmail.com
SYSADMIN=humbfig@gmail.com

MSG="$HOSTNAME UPS $1 Power Failure !!!"
#
(
   echo "$MSG"
   echo " "
   /sbin/apcaccess status
) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
# echo "running script onbattery $MSG"
exit 0
