TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += ISTTOKstates.db
DB += ISTTOKvacuumPumps.db
DB += ISTTOKpcf8574.db
DB += ISTTOKpcf8591.db
DB += ISTTOKpfeiffer.db

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

